embrace-io/embrace-web-sdk

cli/package.json
cli/src/constants.ts
demo/frontend/package-lock.json
demo/frontend/package.json
demo/frontend/src/App.tsx
demo/frontend/src/otel.ts

Another follow-up to #179. We forgot to update several references

fix: update registry name in demo and cli

---

cli/package-lock.json

follow up to https://github.com/embrace-io/embrace-web-sdk/pull/185#discussion_r2027603539

fix: update registry name in cli

---

cli/package-lock.json
cli/package.json
demo/frontend/README.md
demo/frontend/package-lock.json

chore: bump cli version

---

cli/package.json

fix: run npm pkg fix for cli

---

src/utils/PerformanceManager/OTelPerformanceManager.test.ts
src/utils/bulkAddEventListener/bulkAddEventListener.test.ts
src/utils/bulkRemoveEventListener/bulkRemoveEventListener.test.ts
src/utils/generateUUID.test.ts
src/utils/throttle.test.ts
src/utils/withErrorFallback.test.ts

(AI generated)### TL;DR
Added unit tests for utility functions to improve code coverage and reliability.
Added comprehensive test suites for several utility functions:
- `OTelPerformanceManager`: Tests for time calculation methods
- `bulkAddEventListener`: Tests for adding multiple event listeners
- `bulkRemoveEventListener`: Tests for removing multiple event listeners
- `generateUUID`: Tests for UUID generation functionality
- `throttle`: Tests for function throttling behavior
- `withErrorFallback`: Tests for error handling wrapper
Each test suite verifies the core functionality, edge cases, and expected behavior of these utility functions.

test: add more test coverage

---

cli/package.json
cli/src/constants.ts
package.json
src/resources/constants/index.ts

chore: sync cli and sdk versions

---

codecov.yml

For future reference various other things can be configured in this yaml as documented in https://docs.codecov.com/docs/commit-status

chore: add codecov project check

---

src/api-traces/api/TraceAPI/TraceAPI.test.ts
src/api-traces/api/TraceAPI/TraceAPI.ts
src/api-traces/api/TraceAPI/index.ts
src/api-traces/api/TraceAPI/types.ts
src/api-traces/api/index.ts
src/api-traces/index.ts
src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.test.ts
src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.ts
src/api-traces/manager/NoOpTraceManager/index.ts
src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.test.ts
src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.ts
src/api-traces/manager/ProxyTraceManager/index.ts
src/api-traces/manager/index.ts
src/api-traces/manager/types.ts
src/api-traces/traceAPI.test.ts
src/api-traces/traceAPI.ts
src/constants/attributes.ts
src/managers/EmbraceTraceManager/EmbraceTraceManager.test.ts
src/managers/EmbraceTraceManager/EmbraceTraceManager.ts
src/managers/EmbraceTraceManager/index.ts

EMBR-7221 - API For creating performance spans

---

DEVELOPING.md
cli/package-lock.json
cli/package.json
cli/src/constants.ts
demo/frontend/package-lock.json
package-lock.json
package.json
src/resources/constants/index.ts

chore: bump to version 0.0.15

---

src/managers/index.ts
src/sdk/initSDK.test.ts
src/sdk/initSDK.ts

I missed to add that here https://github.com/embrace-io/embrace-web-sdk/pull/226
so currently the Noop is being set and traces are not being sent :(

fix: set global trace manager

---

.github/workflows/ci-nodejs.yml

give github action permissions to write to the repo

ci: give github action permissions to write to the repo

---

.github/workflows/ci-nodejs.yml

address https://github.com/embrace-io/embrace-web-sdk/security/code-scanning/27 using suggestions in https://codeql.github.com/codeql-query-help/javascript/js-actions-command-injection/#recommendation

fix: code injection vulnerability

---

src/sdk/initSDK.test.ts

This test was currently in the `describe('console logging'` section, moving it out and adding a quick additional check that the logs+spans created using the Embrace API end up in the export

test: move initSDK test, add verify export of custom spans and logs

---

cli/package-lock.json
cli/package.json
cli/src/constants.ts
demo/frontend/package-lock.json
package-lock.json
package.json
src/resources/constants/index.ts

chore: bump version

---

.github/workflows/release-drafter.yaml
.github/workflows/release.yaml

fix: add more permissions to release action

fix: add more permissions to release action

---

.github/workflows/release.yaml

ci: add constant files changes to the release PR

ci: add constant files changes to the release PR

---

DEVELOPING.md

Make the release instructions a bit more explicit

chore: update publishing instructions

---

README.md

Fix the name of a package in the docs.

chore: update instrumentation docs

---

.github/workflows/release-drafter.yaml
.github/workflows/release.yaml

... and some other minor CI housekeeping.

chore: pin all 3rd-party GitHub actions

---

.github/workflows/ci-nodejs.yml

fix: test performance ci

---

.github/workflows/release.yaml

fix: support quotes in release body notes

---

.github/workflows/ci-gha-workflows.yaml
.github/workflows/ci-nodejs.yml
.github/workflows/dependency-review.yml
.github/workflows/release.yaml

See https://github.com/zizmorcore/zizmor

Run zizmor for static analysis of .github/workflows/

---

.github/workflows/release.yaml

this is broken as seen in https://github.com/embrace-io/embrace-web-sdk/pull/515

fix: correctly print release body

---

.github/workflows/ci-nodejs.yml
.github/workflows/release.yaml

fix: correct use of bash variables in gha

---

cli/package.json
cli/src/constants.ts
package-lock.json
package.json
src/resources/constants/index.ts

Reverts embrace-io/embrace-web-sdk#517

Revert "release: bump version to 1.5.0"

---

demo/frontend/README.md
demo/frontend/src/App.tsx

Ensure demo log messages match their function.
Fix typo in demo README.
Demo log messages are updated to reflect their log level.

chore: update log messages, fix typo

---

package-lock.json
tests/bundle/vite-7/package-lock.json
tests/bundle/webpack-5/package-lock.json

Repair the conflict between vite 6 and 7 being hoisted, preventing the demo from compiling.
Run the demo locally.

chore: repair package deps

---

demo/frontend-cdn/scripts/runDemo.sh
demo/frontend/package.json
demo/frontend/scripts/runDemo.sh
package-lock.json

Remove hardcoded id in script and package.json
n/a

chore: remove hardcoded app id

---

.github/workflows/ci-nodejs.yml
tests/performance/tests/cdp-performance-tests.spec.ts

Make sure re-run of tests don't cache incorrect results
n/a

fix: re-running failing tests cache

---

rollup.config.js

fix: remove debug id from builds

---

.github/dependabot.yml

fix: playwright dependabot again

---

src/index.ts

Added previously missing exports from sdk: DynamicConfigManager, DynamicSDKConfig, Span

chore: add some missing types

---

README.md

Clarify our browser support, OTel package compatibility, and intent to deprecate CommonJS exports.

chore: add browser support docs

---

src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.ts

Fix the internal name of ClicksInstrumentation.

chore: set clicks instrumentation name

---

tests/integration/tests/__golden__/chromium-next-latest-send-log.json
tests/integration/tests/__golden__/chromium-next-latest-session.json
tests/integration/tests/__golden__/chromium-vite-7-es2015-send-log.json
tests/integration/tests/__golden__/chromium-vite-7-es2015-session.json
tests/integration/tests/__golden__/chromium-vite-7-esnext-send-log.json
tests/integration/tests/__golden__/chromium-vite-7-esnext-session.json
tests/integration/tests/__golden__/chromium-webpack-5-es2015-send-log.json
tests/integration/tests/__golden__/chromium-webpack-5-es2015-session.json
tests/integration/tests/__golden__/chromium-webpack-5-esnext-send-log.json
tests/integration/tests/__golden__/chromium-webpack-5-esnext-session.json
tests/integration/tests/__golden__/firefox-next-latest-send-log.json
tests/integration/tests/__golden__/firefox-next-latest-session.json
tests/integration/tests/__golden__/firefox-vite-7-es2015-send-log.json
tests/integration/tests/__golden__/firefox-vite-7-es2015-session.json
tests/integration/tests/__golden__/firefox-vite-7-esnext-send-log.json
tests/integration/tests/__golden__/firefox-vite-7-esnext-session.json
tests/integration/tests/__golden__/firefox-webpack-5-es2015-send-log.json
tests/integration/tests/__golden__/firefox-webpack-5-es2015-session.json
tests/integration/tests/__golden__/firefox-webpack-5-esnext-send-log.json
tests/integration/tests/__golden__/firefox-webpack-5-esnext-session.json
tests/integration/tests/__golden__/webkit-next-latest-send-log.json
tests/integration/tests/__golden__/webkit-next-latest-session.json
tests/integration/tests/__golden__/webkit-vite-7-es2015-send-log.json
tests/integration/tests/__golden__/webkit-vite-7-es2015-session.json
tests/integration/tests/__golden__/webkit-vite-7-esnext-send-log.json
tests/integration/tests/__golden__/webkit-vite-7-esnext-session.json
tests/integration/tests/__golden__/webkit-webpack-5-es2015-send-log.json
tests/integration/tests/__golden__/webkit-webpack-5-es2015-session.json
tests/integration/tests/__golden__/webkit-webpack-5-esnext-send-log.json
tests/integration/tests/__golden__/webkit-webpack-5-esnext-session.json

fix: update sdk_version in golden files

---

.github/workflows/ci-nodejs.yml
.prettierrc.json
package.json
tests/integration/utils/run-e2e-tests.ts
web-test-runner.config.js

1. Attempt to fix the flaky playwright download timeouts we are seeing.
2. Filter intentional error logs out of wtr output

chore: add back filterLogs, refactor CI to use playwright container

---

tests/integration/platforms/vite-otel-latest/README.md

Update support table with our upgraded versions.

chore: update support table in integration tests doc

---

src/exporters/EmbraceTraceExporter/EmbraceTraceExporter.test.ts

Fixes this failure: https://github.com/embrace-io/embrace-web-sdk/actions/runs/17493719659/job/49705961286

fix: adjust test to work on firefox

---

CLAUDE.md

Introduce a shared Claude Code instruction document.

docs: add CLAUDE.md

---

cli/package.json
package-lock.json
tests/integration/platforms/webpack-4/package.json

Combine recent dependabot changes into a single change.

chore: update commander, looser webpack4 otel deps

---

src/transport/FetchTransport/FetchTransport.ts

This PR https://github.com/embrace-io/embrace-web-sdk/pull/872 seems to have broken the lint.
This aims to fix it.
cc @joaquin-diaz

fix: lint errors
