- demo/frontend/package.json
- demo/frontend/scripts/runDemo.sh
Updated app ID from `pa6hp` to `5przi` in frontend demo configuration.
- Updated the app ID from `pa6hp` to `5przi` in `package.json` for sourcemap upload scripts
- Removed the token parameter (`-t 9819ef05be634fb39720d5f7dffb6404`) from the sourcemap upload commands. THIS WASN'T A VAID TOKEN ANYWAYS, DON'T WORRY ABOUT SECURITY EXPOSURE HERE 😉 
- Updated the app ID in `runDemo.sh` script to use the new app ID when generating the `.env` file
> chore: update demo appID and remove old symbol upload token

- .github/workflows/release-drafter.yaml
Our release drafter action stopped working once we made our repo public. I am guessing this may be due to the conflict of permissions between the public repo and the private action. Here I am copying the setup from https://github.com/embrace-io/embrace-docs which is also public. I will double-check with devops to confirm this approach before merging
> fix: github drafter not working from a public repo

- .github/workflows/ci-nodejs.yml
- README.md
- cli/package.json
- package.json
Update npm publishing configuration to use the public npm registry instead of the private Nexus repository.
- Removed Nexus NPM token configuration from the CI workflow
- Added `NODE_AUTH_TOKEN` environment variable for npm publish
- Added `"publishConfig": { "access": "public" }` to both the main package.json and cli/package.json
- Updated README.md to remove references to the private Nexus repository
- Removed outdated TODOs from README.md related to npm publishing and CI/CD pipeline
> chore: update cicd worflow to publish to npm instead of nexus

- cli/package.json
- package.json
Added package metadata to the CLI package.json file.
Enhanced the CLI package.json file with additional metadata:
- Added bugs reporting information with GitHub issues URL and support email
- Added homepage URL pointing to the GitHub repository
- Added repository information with git URL
- Added relevant keywords for better discoverability (embrace, web, tracking, observability, instrumentation, telemetry, cli)
> chore: add more metadata to the cli package for publishing

- .github/workflows/ci-nodejs.yml
Added `--access public` flag to npm publish command in CI workflow.
Modified the npm publish command in the CI workflow to include the `--access public` flag, ensuring packages are published with public access on npm.
> fix: update visibility from published sdk in npm to be public

- .github/workflows/ci-nodejs.yml
Updated the npm publish authentication token in the CI workflow.
Changed the environment variable used for npm authentication from `secrets.NODE_AUTH_TOKEN` to `secrets.NPMJS_TOKEN` in the GitHub Actions workflow file.
see (internal) slack discussion https://embrace-io.slack.com/archives/C2F256D9U/p1744043199964869?thread_ts=1737747735.789779&cid=C2F256D9U
> fix: update publishing token for npm, using newly created embrace-ci user's token

- .github/workflows/ci-nodejs.yml
Enable npm package provenance for published packages.
- Added `id-token: write` permission to the publish job in the CI workflow
- Updated the npm publish command to include the `--provenance` flag
1. Verify that the CI workflow completes successfully when publishing a package
2. Check that the published package on npm includes provenance information in its metadata
Adding npm provenance provides supply chain security benefits by creating verifiable links between packages and their source code/build environments. This helps users verify that packages were built from the expected source code and through the intended CI process, reducing the risk of compromised packages.
> chore: add provenance linking between npmjs published package and github build

- .github/workflows/ci-nodejs.yml
Add `registry-url: 'https://registry.npmjs.org'` to our github action. I completely missed it in the previous version. See [docs](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)
Specifically the note about 
```
Please note that you need to set the registry-url to https://registry.npmjs.org/ in setup-node to properly configure your credentials.
```
> fix: add missing registry to our publishing GA

- README.md
Explain why sometimes the function name will still be shown minified.
> EMBR-7217 - Explain unsymbolicated function names

- src/api-sessions/api/SessionAPI/SessionAPI.test.ts
- src/api-sessions/manager/NoOpSpanSessionManager/NoOpSpanSessionManager.test.ts
- src/api-sessions/manager/NoOpSpanSessionManager/NoOpSpanSessionManager.ts
- src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.test.ts
- src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.ts
- src/api-sessions/manager/types.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
Support to do:
```typescript
import { session } from '@embrace-io/web-sdk';
session.addBreadcrumb("something happened");
```
> EMBR-7257 - Implement session breadcrumb API

- eslint.config.mjs
Enhanced ESLint configuration with better version mismatch detection and error messages.
- Added descriptive error messages for SDK_VERSION and CLI_VERSION mismatches
- Added a new validation rule to ensure CLI_VERSION matches the SDK version in package.json
- Added a TODO comment about creating a custom ESLint rule to directly compare package versions
- Reformatted the project array in parserOptions for better readability
> chore: validate sdk and cli versions are always in sync

- .github/workflows/ci-nodejs.yml
Copying the publish action for the web sdk, this time for the cli.
> feat: auto publish cli to npm when releasing with GitHub Actions

- .github/workflows/ci-nodejs.yml
- cli/package-lock.json
- cli/package.json
- cli/src/constants.ts
- demo/frontend/package-lock.json
- package-lock.json
- package.json
- src/resources/constants/index.ts
Bugfix: apparently, changing the directory in one step of a job does not persist the current directory across steps because a new shell starts. This should fix it by telling GitHub where to start the shell for the whole job
> fix: github actions change of directory not persisting across steps

- src/api-logs/api/LogAPI/LogAPI.test.ts
- src/api-logs/api/LogAPI/LogAPI.ts
- src/api-sessions/api/SessionAPI/SessionAPI.test.ts
- src/api-sessions/api/SessionAPI/SessionAPI.ts
- src/api-traces/api/TraceAPI/TraceAPI.test.ts
- src/api-traces/api/TraceAPI/TraceAPI.ts
- src/api-users/api/UserAPI/UserAPI.test.ts
- src/api-users/api/UserAPI/UserAPI.ts
This should allow us to do things like:
```
import { session } from '@embrace-io/web-sdk';
session.addBreadcrumb("something happened");
```
> EMBR-7259 - Create high level API that allows calling methods without getting the manager

- src/api-traces/manager/types.ts
- src/managers/EmbraceTraceManager/EmbraceTraceManager.ts
Simplify imports from the OpenTelemetry API by importing both `Span` and `SpanOptions` types directly from the main package instead of importing `SpanOptions` from a build path.
This change only affects type imports and doesn't modify any runtime behavior, so existing tests should continue to pass without modification.
> fix: typescript build broken

- README.md
Doc is wrong, method should be `startPerformanceSpan`
> Fix doc to reflect startPerformanceSpan method

- .github/release-drafter.yml
- .github/workflows/release-drafter.yaml
- DEVELOPING.md
- commitlint.config.js
Enhanced release management with improved automation and versioning strategy.
- Updated release-drafter configuration with:
- Structured categorization for changes (breaking changes, maintenance, bug fixes, features)
- Version resolver based on PR labels (major, minor, patch)
- Autolabeler to automatically categorize PRs based on title and body content
- Improved release template with contributors section
- Simplified release-drafter workflow:
- Added support for PR events to enable auto labeling
- Removed manual version calculation in favor of automated versioning
- Added proper permissions for autolabeler functionality
- Updated DEVELOPING.md with:
- Improved formatting for better readability
- Expanded version bump instructions with additional files to update
- Added documentation …
> ci: adjust github releases workflow to match sem ver

- .github/workflows/ci-nodejs.yml
Remove the conditional check that prevents CI from running on Dependabot PRs and pushes to main. The check for pushes to main will be valuable to make sure squashed commits still have the same format as PR ones
> ci: run commitlint on dependabot PRs and pushes to main too

- commitlint.config.js
Refactor commitlint configuration to use parserPreset instead of custom plugins. The previous approach was reporting always "valid" no matter what was the input 😞 
Testing I did now
Passing
`echo "EMBR-123 fix: something" | npm run commitlint`
`echo "EMBR-123 feat: something" | npm run commitlint`
`echo "fix: something" | npm run commitlint`
Failing
`echo "EMBR-123 something" | npm run commitlint`
`echo "EMBR-123" | npm run commitlint`
`echo "123 feat: something" | npm run commitlint`
`echo "EMBR- feat: something" | npm run commitlint`
> fix: commitlint reporting all false positives

- .github/workflows/ci-nodejs.yml
Typo in our yaml workflow. Double quotes will allow for the version variable to be replaced
> fix: identify the release version

- commitlint.config.js
Disable the `body-max-line-length` rule in the commitlint configuration to allow commit message bodies to exceed 100 characters without triggering validation errors.
Example:  [this](https://github.com/embrace-io/embrace-web-sdk/actions/runs/14411431668/job/40420045031) was failing, and it should pass
> ci: turn off body-max-line-length commitlint rule

- .github/release-drafter.yml
Github already added it by default as a footer, so it was duplicated
> ci: remove CONTRIBUTORS from release template

- .github/workflows/release-drafter.yaml
Github is reporting the pull_request_target events as invalid, the use case for those was an edge case for PRs coming from forks. I can just remove it for now
> ci: remove support for forks to be labeled by the release drafter

- .github/release-drafter.yml
> fix: typo in regex for release drafter autolabeler

- demo/frontend-cdn/package.json
while useful locally, the post install that auto runs after npm install it was just a shortcut, and it won't work in ci environment, so removing the shortcut for now
> fix: remove postinstall script from demo/frontend-cdn

- .github/workflows/ci-nodejs.yml
see Run actions/checkout@v4 job from https://github.com/embrace-io/embrace-web-sdk/actions/runs/14413197888/job/40425376470 as an example. When triggering from a release, you can not commit unless you switch back to main.
Releases always happen from main, and new merges update the latest draft release, still pointing to main, so this is not changing the commit we point at, it is just reenabling the branch.
> fix: make release run from main instead of a detached head so we can commit the bump in the version

- .github/release-drafter.yml
Make EMBR ticket numbers optional in PR titles for autolabeling. This change modifies the regex patterns in the release-drafter.yml file to make the EMBR ticket reference optional when determining PR labels based on title.
Example working from the chrome console now
> ci: make EMBR-XXX identifier optional for autolabeler of PRs

- .github/workflows/ci-nodejs.yml
Update the `actions/checkout@v4` step in the CI workflow to fetch the complete Git history by setting `fetch-depth: 0`. This ensures that the workflow has access to the full commit history, which is likely needed for the subsequent "Extract Version" step to properly determine version information.
Failed action https://github.com/embrace-io/embrace-web-sdk/actions/runs/14447000810/job/40510560985
> ci: checkout not finding main branch on github action

- .github/workflows/ci-nodejs.yml
- package.json
Validate types as part of PRs. This will prevent issues like https://github.com/embrace-io/embrace-web-sdk/pull/244 when we just realized something was broken after merging and while trying to release
> ci: add typescript validation to our ci process

- README.md
- src/api-logs/api/LogAPI/LogAPI.ts
- src/api-logs/manager/NoOpLogManager/NoOpLogManager.ts
- src/api-logs/manager/ProxyLogManager/ProxyLogManager.ts
- src/api-logs/manager/types.ts
- src/instrumentations/exceptions/GlobalExceptionInstrumentation/GlobalExceptionInstrumentation.ts
- src/managers/EmbraceLogManager/EmbraceLogManager.test.ts
- src/managers/EmbraceLogManager/EmbraceLogManager.ts
Change logException to take an optional timestamp parameter. If not received, we use now()
> chore: change logException signature to accept optional timestamp

- .github/workflows/ci-nodejs.yml
ci: give github action permissions to write to the repo at the job level
> ci: give github action permissions to write to the repo at the job level

- src/sdk/index.ts
Let's a user do:
```
const spanRef = useRef<sdk.Span | null>();
useEffect(() => {
spanRef.current = trace.startPerformanceSpan('Wizard flow');
}, []);
```
There's a bunch of OTel interfaces we could probably re-export just sticking with `Span` for now since it is the return type of `startPerformanceSpan`
> chore: re-export Span

- src/sdk/initSDK.test.ts
- src/sdk/initSDK.ts
- src/sdk/registry.ts
- src/sdk/types.ts
I think a few different ways to handle this let me know what you think about this approach, with this we could potentially expose the `registry` to the user for grabbing the setup SDK elsewhere in their app
> chore: protect against the SDK being initialized multiple times

- cli/src/index.ts
- cli/src/processSourceFiles.ts
- cli/src/validateInput.ts
Make the `appVersion` parameter optional in the CLI tool. This change allows the app version to be provided during SDK initialization instead of requiring it as a mandatory CLI parameter. If neither is provided, the SDK will report the app version as "EmbIOAppVersionX.X.X".
The changes have been tested to ensure that:
- The CLI works correctly when `appVersion` is not provided
- The source code processing functions properly with or without an app version
- Input validation correctly handles both cases (with and without app version)
- When an app version is provided, it's still properly injected into the source code
> chore: make app version optional during cli processing

- cli/package-lock.json
- cli/package.json
- cli/src/constants.ts
- demo/frontend/package-lock.json
- package-lock.json
- package.json
- src/resources/constants/index.ts
Bump version from 0.0.15 to 0.0.16 across the web SDK and CLI packages.
Version numbers have been updated in all package.json and package-lock.json files to maintain consistency across the codebase.
> chore: bump version to 0.0.16

- demo/frontend/package-lock.json
- demo/frontend/package.json
Update the sourcemap upload commands to use `embrace-web-cli` instead of `web-cli`.
> fix: web-cli bin name changed, update the demo

- .github/release-drafter.yml
Disable automatic labeling of PRs as 'major' based on 'BREAKING CHANGE' text in the body until we exit beta phase.
> ci: disable release of major versions until we go out of beta

- .github/release-drafter.yml
- .github/workflows/ci-nodejs.yml
- .github/workflows/release-drafter.yaml
- .github/workflows/release.yaml
- DEVELOPING.md
- commitlint.config.js
This PR improves the release process by:
1. Splitting the publishing workflow into separate jobs for SDK and CLI
2. Adding a new workflow for version bumping that:
- Creates a PR with version updates in package.json files
- Labels PRs with "release" tag
3. Updating release-drafter configuration to:
- Exclude PRs with "release" label
- Use a forked version with additional functionality
4. Modifying permissions in CI workflow to be more restrictive
5. Adding "release" as a valid commit type in commitlint config
The new flow works as follows:
1) people create PR with new code
2) those PRs get auto-labeled by release-drafter as patch/minor and also categorized as "feature","fix","maintenance", etc
3) PR gets merged, and no release is created neither in draft nor published
4) a new GitHub …
> ci: new workflow to manually trigger releases going through a PR

- DATA_EXPORT.md
- README.md
- src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.test.ts
- src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.ts
- src/transport/RetryingTransport/constants.ts
Documenting how we export data from the SDK. In reviewing the code I think the only issue I noticed was that we aren't currently ever returning an error as 'retryable' so the retry logic isn't being used: https://github.com/embrace-io/embrace-web-sdk/blob/7276b54b2ca914fbd80bd863457ca06721eaeb1a/src/transport/FetchTransport/FetchTransport.ts#L87
Will file a follow-up for that specifically
> chore: document how data is exported

- .github/workflows/release.yaml
Fix the release workflow by changing the command to create a new branch for the release. Instead of just creating a branch with `git branch`, this PR changes the command to `git checkout -b` which creates the branch and checks it out in one step, ensuring that subsequent operations are performed on the newly created branch.
> fix: checkout new branch during release workflow

- .github/workflows/release-drafter.yaml
Fix the release-drafter workflow by correcting the logic in the `disable-releaser` condition. The current implementation incorrectly disables the releaser when the commit message starts with "release", which is the opposite of the intended behavior. This change inverts the condition to properly enable the releaser only when commit messages start with "release".
> fix: disable releaser when the commit does NOT start with release

- .github/workflows/release.yaml
fix: adjust commit msg to make commitlint happy
example failed action https://github.com/embrace-io/embrace-web-sdk/actions/runs/14498444888/job/40672083380
```
⧗   input: release: Bump version to 0.1.2 (#301)
Co-authored-by: embrace-ci <embrace-ci@users.noreply.github.com>
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
```
> fix: adjust commit msg to make commitlint happy

- .github/workflows/ci-nodejs.yml
Update the CI workflow to trigger deployments when a release is created instead of when it's released (new workflow). This change ensures that non-draft releases will be deployed to production, while maintaining the existing behavior for pushes to main and pull requests.
> ci: setup action to production if a release is created, not only if published

- .github/workflows/ci-nodejs.yml
- .github/workflows/release-drafter.yaml
- DEVELOPING.md
needed to make it a manual step to avoid being published using the GITHUB_TOKEN auth from the release-drafter. That would prevent other action to trigger (the publishing action)
> ci: make the publishing of the release a manual step

- README.md
- demo/frontend/src/App.tsx
- demo/frontend/src/otel.ts
- src/managers/EmbraceUserManager/EmbraceUserManager.test.ts
- src/sdk/initSDK.test.ts
- src/testUtils/FailingStorage/FailingStorage.ts
- src/testUtils/FailingStorage/index.ts
- src/testUtils/index.ts
Clarifying a a few different scenarios that weren't previously in the README:
* how spans that are not ended are treated
* span attribute values must be strings
* setting up console exporters for debugging
* user manager handling cases where storage APIs aren't available
> chore: clarify various behaviours in README and cover with tests

- README.md
This PR updates the README.md documentation 
- Enhances the CDN installation instructions by:
- Replacing the hardcoded version number with a placeholder (X.X.X)
- Adding guidance to check npm for available versions
> docs: adjust cdn version recommendation

- .github/release-drafter.yml
Update the release-drafter configuration to use standardized semantic versioning labels. This change renames the version labels from 'major', 'minor', and 'patch' to 'semver-major', 'semver-minor', and 'semver-patch' respectively. Additionally, it adds the 'dependencies' label to be treated as a patch version change.
I realized dependabot was already labeling its PRs with major minor and patch based on the level of the update from the third party library it was using. This was messing with OUR labeling. For example, if dependabot updates a major version of another library, that would end up meaning a major bump for us. 
This screenshot shows both dependabot labeling and our labeling, ending up with multiple bumping version levels. 
This change add a prefix so we don't conflict with …
> ci: prefix semser version level to avoid conflict with dependabot

- .gitignore
- package.json
- src/api-logs/api/LogAPI/LogAPI.test.ts
- src/api-logs/manager/NoOpLogManager/NoOpLogManager.test.ts
- src/api-logs/manager/ProxyLogManager/ProxyLogManager.test.ts
We weren't validating typescript check for testing files. This PRs adds such check to our PRs `typecheck` github action step.
I am also fixing a couple of error already there that we missed because of this lack of automated check
> fix: validate tests types during cicd integration, fix existing failing type checks

- src/api-traces/api/TraceAPI/TraceAPI.ts
- src/api-traces/api/TraceAPI/index.ts
- src/api-traces/api/TraceAPI/types.ts
- src/api-traces/api/index.ts
- src/api-traces/index.ts
- src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.ts
- src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.ts
- src/api-traces/manager/types.ts
- src/managers/EmbraceTraceManager/EmbraceTraceManager.test.ts
- src/managers/EmbraceTraceManager/EmbraceTraceManager.ts
Added tests to cover creating a performance span with a parent, also ended up adding a `parentSpan` option to the API to make it a bit easier to do
> chore: make sure parents can be set for performance spans

- src/api-sessions/manager/types.ts
- src/common/index.ts
- src/common/types.ts
- src/constants/attributes.ts
- src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.test.ts
- src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.test.ts
- src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.ts
- src/instrumentations/session/SpanSessionVisibilityInstrumentation/types.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
- src/managers/EmbraceSpanSessionManager/types.ts
Adding a configuration parameter to `SpanSessionVisibilityInstrumentation` to have it create sessions when the document becomes hidden, defaulting to false for now
> EMBR-7455 chore: add configuration for creating background sessions

- src/common/index.ts
- src/common/types.ts
- src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.test.ts
- src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.ts
- src/instrumentations/web-vitals/WebVitalsInstrumentation/types.ts
Send current URL with web vitals. In the future we'll update this to send the URL that the browser had when the web vital was reported instead of the current URL to be more accurate 
Unit tests
> EMBR-7483 chore: add current URL to web vitals

- commitlint.config.js
The current length of 100 was a bit restrictive, we were having some dependabot PRs failing due to surpassing this string length: https://github.com/embrace-io/embrace-web-sdk/actions/runs/14763000958/job/41447932730?pr=334
> chore: bump max commit header length

- .github/dependabot.yml
Daily updates are getting a bit too noisy, roll back to weekly
> chore: limit dependabot frequency

- README.md
- demo/frontend/src/App.tsx
- src/api-traces/api/TraceAPI/TraceAPI.test.ts
- src/api-traces/api/TraceAPI/TraceAPI.ts
- src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.test.ts
- src/api-traces/manager/NoOpTraceManager/NoOpTraceManager.ts
- src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.test.ts
- src/api-traces/manager/ProxyTraceManager/ProxyTraceManager.ts
- src/api-traces/manager/types.ts
- src/managers/EmbraceTraceManager/EmbraceTraceManager.test.ts
- src/managers/EmbraceTraceManager/EmbraceTraceManager.ts
- src/sdk/initSDK.test.ts
Rename startPerformanceSpan method to startSpan to avoid the name being related to an internal attribute  
n/a
> chore: [BREAKING CHANGE] rename startPerformanceSpan method to startSpan

- .github/release-drafter.yml
In order for the release drafter to correctly identify breaking changes and bump our version to 1.0.0 we need to define a regex for commits to look for that include "breaking:" at the start the of the message
So far we have included breaking changes in:
* https://github.com/embrace-io/embrace-web-sdk/pull/386 (we'll have to figure out how to relabel this one retroactively)
* https://github.com/embrace-io/embrace-web-sdk/pull/347
> chore: support major releases and breaking changes

- README.md
- commitlint.config.js
- src/api-logs/api/LogAPI/LogAPI.test.ts
- src/api-logs/api/LogAPI/LogAPI.ts
- src/api-logs/manager/NoOpLogManager/NoOpLogManager.test.ts
- src/api-logs/manager/NoOpLogManager/NoOpLogManager.ts
- src/api-logs/manager/ProxyLogManager/ProxyLogManager.test.ts
- src/api-logs/manager/ProxyLogManager/ProxyLogManager.ts
- src/api-logs/manager/index.ts
- src/api-logs/manager/types.ts
- src/instrumentations/exceptions/GlobalExceptionInstrumentation/GlobalExceptionInstrumentation.ts
- src/managers/EmbraceLogManager/EmbraceLogManager.test.ts
- src/managers/EmbraceLogManager/EmbraceLogManager.ts
Make the log API consistent with the other ones we expose where the optional parameters are all grouped together in a single `options` argument after the required ones. Labelling the commit as "feat" so that we bump the minor version since this is a breaking change for the interface (though not the major version since we're still on 0.x)
Added a few more tests where different options are specified / omitted to confirm the defaults are being applied correctly
> breaking: consistently group optional parameters in exported API

- README.md
- src/resources/types.ts
- src/resources/webSdkResource.ts
- src/sdk/initSDK.test.ts
- src/sdk/initSDK.ts
- src/sdk/types.ts
This was close to working as is, just needed to provide a way to to specify a bundle ID placeholder in the app's code in the `initSDK` call when the default placeholder isn't available since our SDK code isn't part of the bundle
> chore: support sourcemap uploads in the CDN case

- src/api-sessions/api/SessionAPI/SessionAPI.test.ts
- src/api-sessions/api/SessionAPI/SessionAPI.ts
- src/api-sessions/manager/NoOpSpanSessionManager/NoOpSpanSessionManager.test.ts
- src/api-sessions/manager/NoOpSpanSessionManager/NoOpSpanSessionManager.ts
- src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.test.ts
- src/api-sessions/manager/ProxySpanSessionManager/ProxySpanSessionManager.ts
- src/api-sessions/manager/types.ts
- src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.test.ts
- src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
- src/managers/EmbraceSpanSessionManager/types.ts
* Add addSessionStartedListener and addSessionEndedListener to hook into the session lifecycle from other instrumentations
* Use addSessionStartedListener and addSessionEndedListener in NavigationInstrumentation
Unit tests and demo app
> chore: automatically end navigation spans on session end

- src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.test.ts
- src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.ts
- src/instrumentations/web-vitals/WebVitalsInstrumentation/types.ts
Wanted to propose this as a way to attribute URLs to the core web vitals we emit instead of always grabbing the current URL at the time of report. Wanted to first validate that this approach makes sense, and then if it did, do some more testing in real environments before we decide if we want it to be the default behaviour (currently the `urlAttribution` config controls this and defaults to false)
> EMBR-7484 feat: option for attributing previous URLs for core web vitals

- rollup.config.js
To suppress rollup warnings about circular dependencies, barrel files, and use of `this` so real errors are easier to spot.
Build output is quieter:
```
> npm run sdk:compile:clean & npm run sdk:compile
> @embrace-io/web-sdk@1.3.0 sdk:compile
> rollup -c && npm run sdk:compile:types
> @embrace-io/web-sdk@1.3.0 sdk:compile:clean
> rimraf build
src/index.ts, src/react/index.ts → build/esm...
created build/esm in 2.1s
src/index.ts, src/react/index.ts → build/esnext...
created build/esnext in 1.5s
src/index.ts, src/react/index.ts → build/src...
created build/src in 1.6s
src/index.ts → build/iife/bundle.js...
created build/iife/bundle.js in 3.1s
> @embrace-io/web-sdk@1.3.0 sdk:compile:types
> tsc --build tsconfig.types.json
```
> chore: suppress acceptable warnings

- eslint.config.mjs
- package-lock.json
- package.json
- src/api-logs/api/LogAPI/LogAPI.test.ts
- src/api-logs/api/LogAPI/LogAPI.ts
- src/api-sessions/api/SessionAPI/SessionAPI.test.ts
- src/api-sessions/api/SessionAPI/SessionAPI.ts
- src/api-traces/api/TraceAPI/TraceAPI.test.ts
- src/api-traces/api/TraceAPI/TraceAPI.ts
- src/api-users/api/UserAPI/UserAPI.ts
- src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.test.ts
- src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.ts
- src/instrumentations/session/SpanSessionBrowserActivityInstrumentation/SpanSessionBrowserActivityInstrumentation.test.ts
- src/instrumentations/session/SpanSessionOnLoadInstrumentation/SpanSessionOnLoadInstrumentation.test.ts
- src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.test.ts
- src/instrumentations/session/SpanSessionTimeoutInstrumentation/SpanSessionTimeoutInstrumentation.ts
- src/instrumentations/session/SpanSessionVisibilityInstrumentation/SpanSessionVisibilityInstrumentation.test.ts
- src/instrumentations/web-vitals/WebVitalsInstrumentation/WebVitalsInstrumentation.test.ts
- src/managers/EmbraceLogManager/EmbraceLogManager.test.ts
- src/managers/EmbraceLogManager/EmbraceLogManager.ts
- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.ts
- src/managers/EmbraceUserManager/EmbraceUserManager.ts
- src/processors/EmbraceLogRecordProcessor/EmbraceLogRecordProcessor.ts
- src/processors/EmbraceProcessor/EmbraceProcessor.ts
- src/processors/IdentifiableSessionLogRecordProcessor/IdentifiableSessionLogRecordProcessor.ts
- src/processors/UserLogRecordProcessor/UserLogRecordProcessor.ts
- src/testUtils/FakeLogRecordProcessor/FakeLogRecordProcessor.ts
1. Preemptively prevent node builtins from being used in web project.
2. Make type imports consistent and without duplicates.
Lint, prettier, and build run successfully.
> chore: add consistent type imports

- .github/workflows/release.yaml
These files no longer exist, they were deleted here: https://github.com/embrace-io/embrace-web-sdk/pull/457
> fix: do not include package-lock.json in release

- .github/workflows/ci-nodejs.yml
`npm ci` was failing since the move to npm packages
> fix: support publishing web-cli with npm workspaces

- rollup.config.js
In addition to using a script tag to load the bundled IIFE version of the sdk, allow users to lazy load: `await import('https://cdn.jsdelivr.net/npm/@embrace-io/web-sdk@1')` 
CDN demo is working.
> feat: explicitly export sdk to window

- rollup.config.js
Prepare for new tooling that leverages debugIds. Read more: https://github.com/tc39/ecma426/blob/main/proposals/debug-id.md
Look at the source of our exported code to see the new comment:
```js
import * as index from './sdk/index.js';
export { index as sdk };
export { session } from './api-sessions/sessionAPI.js';
export { log } from './api-logs/logAPI.js';
export { trace } from './api-traces/traceAPI.js';
export { user } from './api-users/userAPI.js';
//# debugId=9eb21e18-3292-461b-bbed-dadabdf91197
//# sourceMappingURL=index.js.map
```
> chore: add sourcemapDebugIds to rollup

- src/index.ts
- src/instrumentations/index.ts
- src/instrumentations/navigation/index.ts
Added a code snippet here to show how custom navigation instrumentation can be added: https://github.com/embrace-io/embrace-docs/pull/378
Realized there isn't anything React specific in the helper though so wanted to also export `getNavigationInstrumentation` at the top-level so that we can also add a generic example for custom navigation
> chore: export getNavigationInstrumentation

- src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.test.ts
- src/instrumentations/clicks/ClicksInstrumentation/ClicksInstrumentation.ts
- src/instrumentations/clicks/ClicksInstrumentation/types.ts
- src/instrumentations/clicks/ClicksInstrumentation/utils.ts
There's a couple sources of potentially sensitive information from the telemetry we gather automatically:
* Tracking of clicks
* Tracking of network requests
* Appending the current URL as an attribute
Splitting up between PRs, this one is addressing the clicks instrumentation. Adding an option where the user can supply a callback to tell us not to track a click altogether for a particular element. A bit more fine-grained adding a 2nd option to override the friendly representation we make for the clicked element in case its inner text contains something sensitive
Will plan to document in https://embrace.io/docs/web/best-practices/security-considerations/ once the rest of the work is implemented
> EMBR-7913 feat: add configuration options to clicks instrumentation for sensitive data

- web-test-runner.config.js
Resolve this error output in CI test runs:
```
Error:   Failed to scan for dependencies from entries:
/home/runner/work/embrace-web-sdk/embrace-web-sdk/demo/frontend/index.html
/home/runner/work/embrace-web-sdk/embrace-web-sdk/demo/frontend-cdn/index.html
/home/runner/work/embrace-web-sdk/embrace-web-sdk/demo/webpack-example/index.html
/home/runner/work/embrace-web-sdk/embrace-web-sdk/tests/bundle/vite-7/index.html
/home/runner/work/embrace-web-sdk/embrace-web-sdk/tests/performance/public/lighthouse-test.html
/home/runner/work/embrace-web-sdk/embrace-web-sdk/tests/performance/public/performance-test.html
/home/runner/work/embrace-web-sdk/embrace-web-sdk/tests/bundle/webpack-5/public/index.html
✘ [ERROR] Failed to resolve entry for package "@embrace-io/web-sdk". The package may have …
```
> EMBR-8211 chore: resolve CI test run error

- .github/dependabot.yml
- package-lock.json
- package.json
- src/resources/webSdkResource.test.ts
- src/resources/webSdkResource.ts
- src/sdk/initSDK.test.ts
- tests/integration/tests/__golden__/next-latest-send-log.json
- tests/integration/tests/__golden__/next-latest-session.json
- tests/integration/tests/__golden__/vite-7-es2015-send-log.json
- tests/integration/tests/__golden__/vite-7-es2015-session.json
- tests/integration/tests/__golden__/vite-7-esnext-send-log.json
- tests/integration/tests/__golden__/vite-7-esnext-session.json
- tests/integration/tests/__golden__/webpack-5-es2015-send-log.json
- tests/integration/tests/__golden__/webpack-5-es2015-session.json
- tests/integration/tests/__golden__/webpack-5-esnext-send-log.json
- tests/integration/tests/__golden__/webpack-5-esnext-session.json
- tests/integration/utils/test-with-mock-api.ts
Include the stable user_agent.original attribute as described in https://opentelemetry.io/docs/specs/semconv/registry/attributes/user-agent/
> chore: include user_agent.original resource attribute

- .github/dependabot.yml
Set more experimental otel packages as patch-only in dependabot.
Moved `opentelemetry` group up in the file to test if the wildcard was overwriting the rule for the experimental package group. I suspect this is the case because of this behavior: https://github.com/embrace-io/embrace-web-sdk/pull/561
Prettier ran on the yaml file. It's still valid but I can add prettier rules to use double quotes if needed.
> chore: restrict more otel libs in dependabot

- package.json
Typo change: `&` to `&&`.
Directories are deleted before compile starts.
> chore: typo in prepublish script

- .github/dependabot.yml
Prevent dependabot from upgrading otel packages.
> chore: fix the dependabot logic for experimental packages

- .lintstagedrc.mjs
- package.json
Currently, we are running global commands (sometimes twice if cli/src and src/ are changed in the same commit) with staged file names tacked onto the end. The lint commands already include every file in the src folders so there is some unnecessary redundancy.
1. Made a commit outside the src folder - fast.
2. Made a commit inside the src folder - slow. 
3. Made a commit inside the src folder with bad formatting - slow but fixed in the actual commit.
> chore: fix commitlint command

- package-lock.json
- package.json
- src/sdk/types.ts
- tests/integration/platforms/vite-7/src/otel.ts
- tests/integration/platforms/vite-otel-latest/README.md
- tests/integration/platforms/vite-otel-latest/package-lock.json
- tests/integration/platforms/vite-otel-latest/package.json
- tests/integration/platforms/vite-otel-latest/src/main.ts
- tests/integration/platforms/webpack-5/src/otel.ts
Simplify our code by relying directly on `@opentelemetry/sdk-trace-web` package.
Functionally nothing changes because the base package is still a peer dependency.
Compilation succeeds.
> chore: replace opentelemetry/sdk-trace-base with opentelemetry/sdk-trace-web

- tests/integration/utils/run-e2e-tests.ts
This seemed to help locally where I was able to run several times w/ the full suite passing, we can see how it does in CI
> EMBR-8435 chore: try and reduce integration test flakiness by bumping timeouts

- .github/workflows/release.yaml
Adding an update of the golden files sdk version to the version bump job. Ran the commands locally and the output looked good, not sure the best way to test short of merging and then trying to trigger the version bump again
> chore: version bump job should also update goldens

- tsconfig.json
- tsconfig.types.json
We should be less strict about module resolution and more strict about authoring code with ES features newer than 2022, until we actually need them.
Additionally, outDir was redundant because the types file does not export js files.
> chore: optimize tsconfigs for bundlers

- demo/frontend-cdn/scripts/runDemo.sh
- demo/frontend/scripts/runDemo.sh
1. Fix a husky error when installing from the demo workspace.
2. Use helpers commands in the cdn demo.
> chore: use prefix in cdn demos

- package.json
There is a 404 when you follow relative links like REACT.md on jsdelivr.
https://www.jsdelivr.com/package/npm/@embrace-io/web-sdk
> chore: publish all markdown files

- demo/frontend/src/App.tsx
- src/processors/EmbraceNetworkSpanProcessor/EmbraceNetworkSpanProcessor.test.ts
- src/processors/EmbraceNetworkSpanProcessor/types.ts
When network requests are cancelled, or fail due to some other connection error like CORS, the response code is 0:
Our logic for adding `'emb.type': 'perf.network_request'` to network spans was just checking that status code was truthy so was missing this case and we end up treating these as generic root spans in the dashboard
> EMBR-6747 chore: tag cancelled network requests

- package.json
- rollup.config.js
- scripts/measureSize.ts
- src/react-instrumentation/index.ts
- tests/utils/json-to-markdown-table.ts
- Add browser field and export condition for better bundler compatibility
- Add engines field requiring Node.js 18+
- Add default export condition as fallback
- Move React instrumentation from src/react to src/react-instrumentation
- Update build to output CJS files to build/cjs/ instead of build/src/
- Remove esnext build target to simplify build pipeline
- Update measureSize script to work with new build structure
> feat: add browser and default fields to exports

- package.json
- rollup.config.js
1. Using .cjs extension is recommended for commonjs files in module packages. Bundlers are smart but this is a best practice.
2. Accommodate "browser" consumers that still use require()
I recommend we merge this PR after https://github.com/embrace-io/embrace-web-sdk/pull/731
> chore(exports): add browser cjs export, use cjs extension in output

- src/managers/EmbraceSpanSessionManager/EmbraceSpanSessionManager.test.ts
- src/managers/EmbraceUserManager/EmbraceUserManager.test.ts
- src/processors/EmbraceSessionBatchedSpanProcessor/EmbraceSessionBatchedSpanProcessor.test.ts
- src/testUtils/InMemoryStorage/InMemoryStorage.ts
Fix InMemoryStorage test utility to return `null` instead of `undefined`, matching the Web Storage API spec.
- Updated `InMemoryStorage.getItem()` and `key()` to return `null` for missing values
- Fixed test assertions expecting `undefined` to expect `null`
Test-only change. Ensures test environment accurately simulates browser Storage API behavior.
> chore(test): ensure storage methods return null instead of undefined

- cli/package.json
- package-lock.json
Support older versions of node in cli
```bash
❯ npm run demo:frontend:upload:sourcemaps:dry -- -p dist -a abcde -t c668afaf44f9090819df6d8690e1ecc7
> embrace-web-sdk-react-demo@0.0.1 demo:frontend:upload:sourcemaps:dry
> embrace-web-cli upload -d --app-version 0.0.1 -p dist -a abcde -t c668afaf44f9090819df6d8690e1ecc7
Found 4 JavaScript files in directory tree: dist
Processing dist/assets/index-hzLTV2wD.js and dist/assets/index-hzLTV2wD.js.map...
Using debugID 6ea96afb-962c-4470-90f4-21c7f87108d0 from sourceMap for dist/assets/index-hzLTV2wD.js
Dry run mode, not replacing the contents for dist/assets/index-hzLTV2wD.js and dist/assets/index-hzLTV2wD.js.map
Dry run, skipping upload
Uploaded dist/assets/index-hzLTV2wD.js and dist/assets/index-hzLTV2wD.js.map
Processing …
```
> chore: lower node version requirement to v20 for cli

- cli/.gitignore
- cli/.prettierrc.json
- cli/package.json
- cli/tsconfig.json
- package-lock.json
I was looking for opportunities to make our bundle smaller and it turned it into a full review of the cli package. There are no functional changes, just housekeeping.
- Switched from TypeScript compiler to tsup bundler for faster builds
- Reduced Node.js requirement from 20.0.0 to 18.0.0 for broader compatibility
- Removed unnecessary configuration files (.gitignore, .prettierrc.json)
- Streamlined package.json scripts and removed redundant exports
- Added es-check and publint for package validation
- Updated tsconfig to ES2022 target with noEmit for type checking only
- Reduced dev dependencies from 10 to 4 packages
I ran the demo with an appID but I would like someone to do a prod upload to fully test.
> refactor(cli): faster tools, lower node req to 18

- src/sdk/initSDK.test.ts
After the last OTel version bump, initSDK tests needed an update.
> chore: update testing otel version

- .github/dependabot.yml
Our integration tests were excluded from OTel version updates.
This attempts to fix dependabot webpack 4 and otel-latest logic.
> chore: lock webpack 4 version, force otel-latest updates

- .github/dependabot.yml
The webpack-4 test directory should maintain the same major versions that would be installed in a typical webpack 4 project.
> chore: pin webpack 4 deps to current majors

- .github/workflows/ci-nodejs.yml
- cli/package.json
- package-lock.json
- package.json
- scripts/validate-build.sh
- scripts/validate-cli.sh
Once I added es-check and publint, it made sense to merge all the kinds of validation into one command.
- Add validation scripts for SDK and CLI builds to ensure quality and catch regressions
- Scripts run automatically in CI after builds complete
- Configurable size limits via environment variables
- Add `scripts/validate-build.sh` for SDK validation
- Add `scripts/validate-cli.sh` for CLI validation  
- Add `validate` commands to package.json
- Integrate validation into CI workflow
- ES6/ES2022 compatibility via es-check
- Package publishing readiness via publint
- Bundle size limits (configurable, default 47KB gzipped)
- ESM and CommonJS exports work correctly
- Sourcemap validity and completeness
- Load performance benchmarking
- No unexpected require() calls in distribution files
- …
> feat(build): add build validation scripts

- src/sdk/initSDK.test.ts
- src/sdk/initSDK.ts
- src/sdk/types.ts
Adding a check to avoid running when the protocol is "file:", making this configurable in case anyone wants to override the default
> EMBR-8655 chore: avoid running under restricted protocols

- src/sdk/initSDK.test.ts
Some of the unit tests in `initSDK.test.ts` where making real fetch requests to the config endpoint, these would take an inconsistent amount of time to complete resulting in the flakiness because in some cases they would end up writing a 'embrace_remote_config' key to local storage after we had cleared it in the test setup
> chore: prevent real config request from being made in tests

- src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.test.ts
- src/instrumentations/navigation/NavigationInstrumentation/NavigationInstrumentation.ts
Trying to address: https://github.com/embrace-io/embrace-web-sdk/security/code-scanning/37
I'm not quite sure how to change this regex into a version that doesn't trigger the warning but was going to give this as a first try since it makes the regex more specific while preserving the behaviour. Another suggestion from the issue to try if this doesn't work is checking that `route.path` is some reasonable length like < 1000
> fix: try and address js/polynomial-redos warning
